name: FE-e2e run on Cypress cloud

on:
  # pull_request:
  #   types:[opened, synchronize, reopened]
  push:
    branches: [main, AddGHA]
    # branches-igore
    # tags:
    # tags-ignore:
  schedule:
    - cron: '25 9 * * *'
  workflow_dispatch:
      inputs:
        nodejs-version:
          type: string
          default: '20'
        featurePath:
          type: string
          default: 'cypress/e2e/search.feature'

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    environment: UAT
    env:
      CYPRESS_BaseURL: ${{ vars.CYPRESS_BaseURL }}
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
          registry-url: 'http://registry.npmjs.org'
      - name: debug
        run: echo "cypress baseurl is $CYPRESS_BaseURL"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          # build: npm run build
          # start: npm start
          record: true
          spec: cypress/e2e/search.feature
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: ${{ secrets.CRPRESS_PROJECT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
